### ISSUE TITLE
Instagram page won't open in AppGallery

### ISSUE THREAD

**Issue by orionsolex** [deakjahn/flutter_launch_store#2]
cant open application page in AppGallery

`StoreLauncher.openWithStore('com.instagram.android.huawei)`

please help
![image](https://github.com/deakjahn/flutter_launch_store/assets/83350925/ba67678a-ae24-46b9-9c5f-cb2dde943f3b)

![image](https://github.com/deakjahn/flutter_launch_store/assets/83350925/c3b5bdf7-3d9d-4fcf-8b31-980af7fe1fdf)

**Comment by deakjahn** [comment]
Are you sure that it exists? The search https://appgallery.huawei.com/#/search/instagram doesn't find it.

**Comment by orionsolex** [comment]
I do it as in the instructions for the package:


![image](https://github.com/deakjahn/flutter_launch_store/assets/83350925/650d10e7-954a-4e75-9ac9-0765a0e2360a)
![image](https://github.com/deakjahn/flutter_launch_store/assets/83350925/a173c057-5048-41fc-980d-03db7e0af0e4)


ср, 24 янв. 2024 г. в 16:27, Gábor ***@***.***>:

**Comment by orionsolex** [comment]
and search result is fine
![image](https://github.com/deakjahn/flutter_launch_store/assets/83350925/b8e422d7-ad5b-4875-a798-cfeb5e26ccaf)


ср, 24 янв. 2024 г. в 16:32, Леонид Тарасович ***@***.***>:

**Comment by deakjahn** [comment]
It's not really a question of instructions but simply, it looks like `com.instagram.android.huawei` doesn't exist in the AppGallery. If there's no such page, there's nothing to open there.

This is probably due to the trade restrictions between Huawei and the United States. I don't think Instagram can appear in the Huawei store without breaking their law in the US.

**Comment by orionsolex** [comment]
Instagram for example, in reality I need to display the page of my application.
Can you test the functionality on another app published in the store?

**Comment by deakjahn** [comment]
I use the plugin in all my apps and they all appear correctly, both Google Play Store and AppGallery. I don't have an iOS device to check, although I do have apps over there, too.

**Comment by deakjahn** [comment]
Now I see that you're trying in the emulator. I don't think the proper Google Play Services are installed there, it wasn't the last time I checked. And even if the Play Store is there, the Huawei AppGallery won't be for sure. Try it on a real device instead.
